CREATE TABLE IF NOT EXISTS orders_data.stg_orders
(
ORDER_NUMBER STRING,
SHIPPED_DATE TIMESTAMP,
STATUS STRING,
COMMENTS STRING,
CUSTOMER_NUMBER STRING,
CUSTOMER_NAME STRING,
CUST_CITY STRING,
CUST_STATE STRING,
CUST_COUNTRY STRING,
CUST_COUNTRY_ISO STRING,
SALES_CURRENCY STRING,
SALES_REP_ID INT,
SALES_REP_FIRSTNAME STRING,
SALES_REP_LASTNAME STRING,
OFFICE_CODE STRING,
REPORTING_PATH ARRAY<INT>,
OFFICE_CITY STRING,
OFFICE_STATE STRING,
OFFICE_TERRITORY STRING,
OFFICE_COUNTRY STRING
)
PARTITIONED BY (ORDER_YEAR STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
COLLECTION items terminated by ','
STORED AS TEXTFILE;


insert overwrite table orders_data.stg_orders partition(ORDER_YEAR='2003') select ORDER_NUMBER, SHIPPED_DATE, STATUS, COMMENTS,CUSTOMER_NUMBER,CUSTOMER_NAME,CUST_CITY,CUST_STATE,CUST_COUNTRY,CUST_COUNTRY_ISO, SALES_CURRENCY,SALES_REP_ID,SALES_REP_FIRSTNAME,SALES_REP_LASTNAME,OFFICE_CODE,REPORTING_PATH,OFFICE_CITY,OFFICE_STATE, OFFICE_TERRITORY,OFFICE_COUNTRY from orders_data.orders ord WHERE year(ord.order_date)='2003';

insert into table orders_data.stg_orders partition(ORDER_YEAR='2004') select ORDER_NUMBER, SHIPPED_DATE, STATUS, COMMENTS,CUSTOMER_NUMBER,CUSTOMER_NAME,CUST_CITY,CUST_STATE,CUST_COUNTRY,CUST_COUNTRY_ISO, SALES_CURRENCY,SALES_REP_ID,SALES_REP_FIRSTNAME,SALES_REP_LASTNAME,OFFICE_CODE,REPORTING_PATH,OFFICE_CITY,OFFICE_STATE, OFFICE_TERRITORY,OFFICE_COUNTRY from orders_data.orders ord WHERE year(ord.order_date)='2004';

insert into table orders_data.stg_orders partition(ORDER_YEAR='2005') select ORDER_NUMBER, SHIPPED_DATE, STATUS, COMMENTS,CUSTOMER_NUMBER,CUSTOMER_NAME,CUST_CITY,CUST_STATE,CUST_COUNTRY,CUST_COUNTRY_ISO, SALES_CURRENCY,SALES_REP_ID,SALES_REP_FIRSTNAME,SALES_REP_LASTNAME,OFFICE_CODE,REPORTING_PATH,OFFICE_CITY,OFFICE_STATE, OFFICE_TERRITORY,OFFICE_COUNTRY from orders_data.orders ord WHERE year(ord.order_date)='2005';