CREATE TABLE orders_data.dim_status (
    STATUS_KEY INT,
    STATUS STRING
)
STORED AS orc;

CREATE TEMPORARY TABLE tempstatus AS SELECT DISTINCT STATUS FROM ORDERS_DATA.ORDERS;

SELECT ROW_NUMBER() OVER (ORDER BY STATUS) STATUS_KEY,STATUS FROM tempstatus;

INSERT INTO orders_data.dim_status SELECT ROW_NUMBER() OVER (ORDER BY STATUS) STATUS_KEY,STATUS FROM tempstatus;

--------------------------------------------------
--------------------------------------------------

CREATE TABLE orders_data.dim_product (
    PRODUCT_KEY INT,
    PRODUCT_CODE STRING,
    PRODUCT_NAME STRING,
    PRODUCT_CATEGORY STRING,
    PRODUCT_VENDOR STRING
)
STORED AS orc;

CREATE TEMPORARY TABLE tempproduct AS SELECT DISTINCT PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_VENDOR FROM orders_data.orderdetails;

SELECT ROW_NUMBER() OVER (ORDER BY PRODUCT_CODE) PRODUCT_KEY, PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_VENDOR FROM tempproduct;

INSERT INTO orders_data.dim_product SELECT ROW_NUMBER() OVER (ORDER BY PRODUCT_CODE) PRODUCT_KEY, PRODUCT_CODE,PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_VENDOR FROM tempproduct;