CREATE TABLE IF NOT EXISTS orders_data.stg_order_details (
    ORDER_NUMBER BIGINT,
    PRODUCT_CODE STRING,
    PRODUCT_NAME STRING,
    PRODUCT_CATEGORY STRING,
    PRODUCT_VENDOR STRING,
    QUANTITY_IN_STOCK INT,
    BUY_PRICE DECIMAL,
    QUANTITY_ORDERED INT,
    UNIT_PRICE DECIMAL
)
STORED AS orc;

CREATE EXTERNAL TABLE IF NOT EXISTS orders_data.delta_order_details
(
ORDER_NUMBER STRING,
PRODUCT_CODE STRING,
PRODUCT_NAME STRING,
PRODUCT_CATEGORY STRING,
PRODUCT_VENDOR STRING,
QUANTITY_IN_STOCK STRING,
BUY_PRICE STRING,
QUANTITY_ORDERED STRING,
UNIT_PRICE STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION '/user/cloudera/RawData/OrderDetailsData'
tblproperties ("skip.header.line.count"="1");


INSERT INTO orders_data.stg_order_details
SELECT CAST(ORDER_NUMBER AS BIGINT), PRODUCT_CODE, PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_VENDOR,
CAST(QUANTITY_IN_STOCK AS INT),CAST(BUY_PRICE AS DECIMAL(10,2)), CAST(QUANTITY_ORDERED AS INT), CAST(UNIT_PRICE AS DECIMAL(10,2))
FROM orders_data.delta_order_details;
